### ISSUE TITLE
Very good job,love from China XD

### ISSUE THREAD

**Issue by Initial-heart-1** [843773493/Hiden_desktop_icon#2]
~~非常好工作，爱来自中国（~~
这个项目很棒，让我终于能好好看看壁纸了！但是有一些建议：
- 配置项可能使用英文好些？可以辅以中文注释，这样兼容性可能会更好些。
- 驼峰命名很好没错啦，但是确定是 `deskTop...` 而不是 `desktop...` 吗？
- 能否进一步开发，支持在存在窗口未最小化时自动最小化并隐藏图标，在重新进入活动状态时自动恢复？类似于屏保的样子。
- 软件是中文，代码有中文，命名也是中文，为啥 README 是英文的啊......建议提供中文版本并作为默认（README.md），另提供 README_en.md。

一点建议，我也不是很懂，如有冒犯请多包涵~感谢你将这么好的项目开源出来！期待你的更多作品！

**Comment by Initial-heart-1** [comment]
哦对了，我是说，有没有这样一种可能，只是可能
Release 和 Repo 对不上？是不是忘记传码了 QAQ

**Comment by Initial-heart-1** [comment]
跟人再 Review 了一下，另外提出一点点问题：
- QT 可以捕获键鼠事件，不需要额外引入第三方库了。
- 全都是 QT 为啥不直接用 CPP 写啊......
- 看得出来辅助编码的痕迹很重，不如重构一下？

**Comment by 843773493** [comment]
你好，感谢你对我的项目的关注和建议！😊

我很高兴你喜欢这个项目，能让你更好地欣赏壁纸。我已经根据你的建议做了一些改进：

-  我增加了一个新功能，支持在存在窗口未最小化时自动最小化并隐藏图标，在重新进入活动状态时自动恢复，就像屏保一样。
- 我提供了中文版本的 README.md，并把英文版本改成了 README_en.md。

你可以在我的项目页面上看到这些更新。如果你有任何问题或反馈，请随时告诉我。我很感激你的支持和鼓励！期待你的更多意见！👍

- 配置文件用中文是我当时想看看用中文会不会出BUG，结果没有。
- Release 和 Repo的问题我是随便传的，没注意。
- 最开始我没用QT界面，直接在网上挑了个好用的捕获键鼠事件的python库。
- 小程序用python又快又稳。
- 辅助编码的痕迹问题不大吧，反正也不大，随意点了。

**Comment by Initial-heart-1** [comment]
为什么一股扑面而来的 GPT 味（
